[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.465023.xyz", custom_domain = true },
  { pattern = "quay.465023.xyz", custom_domain = true },
  { pattern = "gcr.465023.xyz", custom_domain = true },
  { pattern = "k8s-gcr.465023.xyz", custom_domain = true },
  { pattern = "k8s.465023.xyz", custom_domain = true },
  { pattern = "ghcr.465023.xyz", custom_domain = true },
  { pattern = "cloudsmith.465023.xyz", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.mydomain.com", custom_domain = true }
